/* soapClient.cpp
   Generated by gSOAP 2.8.21 from weather.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.21 2015-03-29 05:28:30 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetWeather(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetWeather *ns1__GetWeather, _ns1__GetWeatherResponse &ns1__GetWeatherResponse)
{	struct __ns1__GetWeather soap_tmp___ns1__GetWeather;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webservicex.net/globalweather.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.webserviceX.NET/GetWeather";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetWeather.ns1__GetWeather = ns1__GetWeather;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetWeather(soap, &soap_tmp___ns1__GetWeather);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetWeather(soap, &soap_tmp___ns1__GetWeather, "-ns1:GetWeather", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetWeather(soap, &soap_tmp___ns1__GetWeather, "-ns1:GetWeather", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetWeatherResponse)
		return soap_closesock(soap);
	ns1__GetWeatherResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetWeatherResponse.soap_get(soap, "ns1:GetWeatherResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetCitiesByCountry(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetCitiesByCountry *ns1__GetCitiesByCountry, _ns1__GetCitiesByCountryResponse &ns1__GetCitiesByCountryResponse)
{	struct __ns1__GetCitiesByCountry soap_tmp___ns1__GetCitiesByCountry;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webservicex.net/globalweather.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.webserviceX.NET/GetCitiesByCountry";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetCitiesByCountry.ns1__GetCitiesByCountry = ns1__GetCitiesByCountry;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetCitiesByCountry(soap, &soap_tmp___ns1__GetCitiesByCountry);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetCitiesByCountry(soap, &soap_tmp___ns1__GetCitiesByCountry, "-ns1:GetCitiesByCountry", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetCitiesByCountry(soap, &soap_tmp___ns1__GetCitiesByCountry, "-ns1:GetCitiesByCountry", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetCitiesByCountryResponse)
		return soap_closesock(soap);
	ns1__GetCitiesByCountryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetCitiesByCountryResponse.soap_get(soap, "ns1:GetCitiesByCountryResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetWeather_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetWeather *ns1__GetWeather, _ns1__GetWeatherResponse &ns1__GetWeatherResponse)
{	struct __ns1__GetWeather_ soap_tmp___ns1__GetWeather_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webservicex.net/globalweather.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.webserviceX.NET/GetWeather";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetWeather_.ns1__GetWeather = ns1__GetWeather;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetWeather_(soap, &soap_tmp___ns1__GetWeather_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetWeather_(soap, &soap_tmp___ns1__GetWeather_, "-ns1:GetWeather", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetWeather_(soap, &soap_tmp___ns1__GetWeather_, "-ns1:GetWeather", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetWeatherResponse)
		return soap_closesock(soap);
	ns1__GetWeatherResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetWeatherResponse.soap_get(soap, "ns1:GetWeatherResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetCitiesByCountry_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetCitiesByCountry *ns1__GetCitiesByCountry, _ns1__GetCitiesByCountryResponse &ns1__GetCitiesByCountryResponse)
{	struct __ns1__GetCitiesByCountry_ soap_tmp___ns1__GetCitiesByCountry_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webservicex.net/globalweather.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.webserviceX.NET/GetCitiesByCountry";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetCitiesByCountry_.ns1__GetCitiesByCountry = ns1__GetCitiesByCountry;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetCitiesByCountry_(soap, &soap_tmp___ns1__GetCitiesByCountry_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetCitiesByCountry_(soap, &soap_tmp___ns1__GetCitiesByCountry_, "-ns1:GetCitiesByCountry", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetCitiesByCountry_(soap, &soap_tmp___ns1__GetCitiesByCountry_, "-ns1:GetCitiesByCountry", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetCitiesByCountryResponse)
		return soap_closesock(soap);
	ns1__GetCitiesByCountryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetCitiesByCountryResponse.soap_get(soap, "ns1:GetCitiesByCountryResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
